### ISSUE TITLE
Some questions about extract_features_detectron.py.

### ISSUE THREAD

**Issue by zefanZhang-cn** [shubhamagarwal92/visdial_conv#21]
I am very interested in your work. But when I try to extract features from my own subset, i did not find the files of "data/config_faster_rcnn_x101.yaml"and"data/model_faster_rcnn_x101.pkl" .Could you please give me some help? Thanks a lot.

**Comment by shubhamagarwal92** [comment]
Hi @Gorgeous-gift 
Thank you for your interest in our work. 

We have provided a [shell script](https://github.com/shubhamagarwal92/visdial_conv/blob/master/setup_visdial/setup.sh ) to streamline the setup process. Basically follow the code [here](https://github.com/shubhamagarwal92/visdial_conv/blob/master/setup_visdial/setup.sh#L42). 

 You can also download the data from the [original repo](https://github.com/batra-mlp-lab/visdial-challenge-starter-pytorch#download-data).

**Comment by zefanZhang-cn** [comment]
> Hi @Gorgeous-gift Thank you for your interest in our work.
> 
> We have provided a [shell script](https://github.com/shubhamagarwal92/visdial_conv/blob/master/setup_visdial/setup.sh) to streamline the setup process. Basically follow the code [here](https://github.com/shubhamagarwal92/visdial_conv/blob/master/setup_visdial/setup.sh#L42).
> 
> You can also download the data from the [original repo](https://github.com/batra-mlp-lab/visdial-challenge-starter-pytorch#download-data).

Thank you very much!

**Comment by zefanZhang-cn** [comment]
> Hi @Gorgeous-gift Thank you for your interest in our work.
> 
> We have provided a [shell script](https://github.com/shubhamagarwal92/visdial_conv/blob/master/setup_visdial/setup.sh) to streamline the setup process. Basically follow the code [here](https://github.com/shubhamagarwal92/visdial_conv/blob/master/setup_visdial/setup.sh#L42).
> 
> You can also download the data from the [original repo](https://github.com/batra-mlp-lab/visdial-challenge-starter-pytorch#download-data).

Thanks for your reply. But my question is that the two files in the ’extract_features_detectron.py‘, i want to extract features  again，rather than features that have already been extracted.

**Comment by shubhamagarwal92** [comment]
Hi @Gorgeous-gift 
We used pre-computed features in our work. However, you could refer to the [visdial challenge starter code](https://github.com/batra-mlp-lab/visdial-challenge-starter-pytorch#download-data) if you want to extract features again. 

I can also point you to this [work](https://github.com/yuleiniu/rva#extracting-features-optional) which I know also provide some [config](https://github.com/yuleiniu/rva/blob/master/data/config_faster_rcnn_x101.yaml) and similar code to extract features.

**Comment by zefanZhang-cn** [comment]
> Hi @Gorgeous-gift We used pre-computed features in our work. However, you could refer to the [visdial challenge starter code](https://github.com/batra-mlp-lab/visdial-challenge-starter-pytorch#download-data) if you want to extract features again.
> 
> I can also point you to this [work](https://github.com/yuleiniu/rva#extracting-features-optional) which I know also provide some [config](https://github.com/yuleiniu/rva/blob/master/data/config_faster_rcnn_x101.yaml) and similar code to extract features.

Thanks for your help. I finally found them.

**Comment by shubhamagarwal92** [comment]
Closing this now! @Gorgeous-gift please feel free to reopen or ask any other question! Good luck!
