### ISSUE TITLE
Is the code complete

### ISSUE THREAD

**Issue by weichentangming** [shubhamagarwal92/visdial_conv#3]
Is the code complete？

**Comment by shubhamagarwal92** [comment]
Hi @weichentangming  

Thanks for your interest in our work. I will be releasing the code soon. (Hopefully by this week!)

**Comment by shubhamagarwal92** [comment]
Hi @weichentangming 

I have released a v0.1 of our code. Please try it out and let me know if it works for you. 

I will be providing a cleaner version in future releases. Please bear with me :)  

Thanks.

**Comment by weichentangming** [comment]
thank you for your code. I will try it out

**Comment by weichentangming** [comment]
thank you for your code. I will try it out

**Comment by shubhamagarwal92** [comment]
Sure. Good luck with your research! Closing this issue now.
