### ISSUE TITLE
where is the file "visdialch/utils/emb_file_paths"?

### ISSUE THREAD

**Issue by vanchen523** [shubhamagarwal92/visdial_conv#6]
No module named 'visdialch.utils.emb_file_paths'.

**Comment by shubhamagarwal92** [comment]
Hi @vanchen523 

Thanks for pointing that out. I have added a commit for the same https://github.com/shubhamagarwal92/visdial_conv/commit/555e46c2281e66a74d2a4a4ae3bb5babe842ce18 
Please take a pull and let me know if there is any other problem.

**Comment by shubhamagarwal92** [comment]
Closing this now. Feel free to ask any further questions.
